# Tugas 2 DPP
# Soal
Buat Dictionary (Bobot Penilaian 15 Point):
p1 : nama=>Budi, jabatan=> Manager, agama=>Islam, status=>Menikah
p2 : nama=>Siti, jabatan=> Asisten Manager, agama=>Islam, status=>Menikah
p3 : nama=>I Gede, jabatan=> Supervisor, agama=>Hindu, status=>Menikah
p4 : nama=>Joko, jabatan=> Staff, agama=>Islam, status=>Belum Menikah
p5 : nama=>Alex, jabatan=> Staff, agama=>Kristen Protestan, status=>Belum Menikah

Semua pegawai masukkan ke sebuah list dengan nama ar_pegawai (Bobot Penilaian 5 Point)

Cetaklah Slip Gaji Pegawai Menggunakan Nested Loop Dengan Data:

- Nama (Bobot Penilaian 5 Point)
- Jabatan (Bobot Penilaian 5 Point)
- Agama (Bobot Penilaian 5 Point)
- Status (Bobot Penilaian 5 Point)
- Gaji Pokok: (Bobot Penilaian 10 Point)
Gunakan kondisional if:
(Manager=>15 jt, Asmen=>10 jt, Supervisor=>7 jt, Staff=> 4jt)
- Tunjangan jabatan => 30% dari gapok (Bobot Penilaian 5 Point)
- BPJS = 10 % dari gapok (Bobot 5 Penilaian Point)
- Tunjangan keluarga: (Bobot Penilaian 10 Point)
Gunakan Tuple & List
10% dari gapok untuk yg sudah menikah
- Gaji Kotor (Jumlahkan semua element gaji) (Bobot Penilaian 5 Point)
- Zakat Profesi 2,5% (Bobot Penilaian 10 Point)
(gunakan tuple list: untuk pegawai muslim dan minimal gaji kotor 7 jt )
- Gaji Bersih => Gaji Kotor - Zakat Profesi - BPJS (Bobot Penilaian 5 Point)

In [ ]:
# Jawab
p1 = {'nama':'Budi', 'jabatan':'Manager', 'agama':'Islam', 'status':'Menikah'}
p2 = {'nama':'Siti', 'jabatan':'Asisten Manager', 'agama':'Islam', 'status':'Menikah'}
p3 = {'nama':'I Gede', 'jabatan':'Supervisor', 'agama':'Hindu', 'status':'Menikah'}
p4 = {'nama':'Joko', 'jabatan':'Staff', 'agama':'Islam', 'status':'Belum Menikah'}
p5 = {'nama':'Alex', 'jabatan':'Staff', 'agama':'Kristen Protestan', 'status':'Belum Menikah'}

ar_pegawai = [p1, p2, p3, p4, p5]

# akses data pegawai
print("Data Pegawai:")
for pegawai in ar_pegawai:
  data = f'nama: {pegawai["nama"]}, jabatan: {pegawai["jabatan"]}, agama: {pegawai["agama"]}, status: {pegawai["status"]}'
  print(data)

print("\n===Slip Gaji Pegawai:===")

# Menentukan Gaji
for pegawai in ar_pegawai:
  if pegawai["jabatan"] == "Manager":
    gajiPokok = 15000000
  elif pegawai["jabatan"] == "Asisten Manager":
      gajiPokok = 10000000
  elif pegawai["jabatan"] == "Supervisor":
    gajiPokok = 7000000
  elif pegawai["jabatan"] == "Staff":
    gajiPokok = 4000000

  tunjanganJabatan = 0.3 * gajiPokok
  bpjs = 0.1 * gajiPokok
  tunjanganKeluarga = (0, 0.10 * gajiPokok)[pegawai["status"] == "Menikah"]
  gajiKotor = gajiPokok + tunjanganJabatan + tunjanganKeluarga - bpjs
  zakatProfesi = (0, 0.025 * gajiPokok)[pegawai["agama"] == "Islam" and gajiKotor >= 7000000]
  gajiBersih = gajiKotor - zakatProfesi


  # Print hasil
  print("\nData Pegawai ke-", ar_pegawai.index(pegawai)+1,
            "\n================================="
            "\nNama\t\t\t:", pegawai["nama"],
            "\nJabatan\t\t\t:", pegawai["jabatan"],
            "\nAgama\t\t\t:", pegawai["agama"],
            "\nStatus\t\t\t:", pegawai["status"],
            "\nGaji\t\t\t: Rp {:,.0f}".format(gajiPokok),
            "\nTunjangan Jabatan\t: Rp {:,.0f}".format(tunjanganJabatan),
            "\nBPJS\t\t\t: Rp {:,.0f}".format(bpjs),
            "\nTunjangan Keluarga\t: Rp {:,.0f}".format(tunjanganKeluarga),
            "\nGaji Kotor\t\t: Rp {:,.0f}".format(gajiKotor),
            "\nZakat Profesi\t\t: Rp {:,.0f}".format(zakatProfesi),
            "\nGaji Bersih\t\t: Rp {:,.0f}".format(gajiBersih),
            "\n=================================")

Data Pegawai:
nama: Budi, jabatan: Manager, agama: Islam, status: Menikah
nama: Siti, jabatan: Asisten Manager, agama: Islam, status: Menikah
nama: I Gede, jabatan: Supervisor, agama: Hindu, status: Menikah
nama: Joko, jabatan: Staff, agama: Islam, status: Belum Menikah
nama: Alex, jabatan: Staff, agama: Kristen Protestan, status: Belum Menikah

===Slip Gaji Pegawai:===

Data Pegawai ke- 1
=================================
Nama			: Budi
Jabatan			: Manager
Agama			: Islam
Status			: Menikah
Gaji			: Rp 15,000,000
Tunjangan Jabatan	: Rp 4,500,000
BPJS			: Rp 1,500,000
Tunjangan Keluarga	: Rp 1,500,000
Gaji Kotor		: Rp 19,500,000
Zakat Profesi		: Rp 375,000
Gaji Bersih		: Rp 19,125,000
=================================

Data Pegawai ke- 2
=================================
Nama			: Siti
Jabatan			: Asisten Manager
Agama			: Islam
Status			: Menikah
Gaji			: Rp 10,000,000
Tunjangan Jabatan	: Rp 3,000,000
BPJS			: Rp 1,000,000
Tunjangan Keluarga	: Rp 1,000,000
Gaji Kotor		: Rp 13,000,000
Zakat Profesi		: Rp 250,000
Gaji Bersih		: Rp 12,750,000
=================================

Data Pegawai ke- 3
=================================
Nama			: I Gede
Jabatan			: Supervisor
Agama			: Hindu
Status			: Menikah
Gaji			: Rp 7,000,000
Tunjangan Jabatan	: Rp 2,100,000
BPJS			: Rp 700,000
Tunjangan Keluarga	: Rp 700,000
Gaji Kotor		: Rp 9,100,000
Zakat Profesi		: Rp 0
Gaji Bersih		: Rp 9,100,000
=================================

Data Pegawai ke- 4
=================================
Nama			: Joko
Jabatan			: Staff
Agama			: Islam
Status			: Belum Menikah
Gaji			: Rp 4,000,000
Tunjangan Jabatan	: Rp 1,200,000
BPJS			: Rp 400,000
Tunjangan Keluarga	: Rp 0
Gaji Kotor		: Rp 4,800,000
Zakat Profesi		: Rp 0
Gaji Bersih		: Rp 4,800,000
=================================

Data Pegawai ke- 5
=================================
Nama			: Alex
Jabatan			: Staff
Agama			: Kristen Protestan
Status			: Belum Menikah
Gaji			: Rp 4,000,000
Tunjangan Jabatan	: Rp 1,200,000
BPJS			: Rp 400,000
Tunjangan Keluarga	: Rp 0
Gaji Kotor		: Rp 4,800,000
Zakat Profesi		: Rp 0
Gaji Bersih		: Rp 4,800,000
=================================